spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/medserv
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    driver-class-name: org.postgresql.Driver
  thymeleaf:
    cache: false
  sql:
    init:
      mode: never

server:
  port: 8080

app:
  properties:
    version: 1.0
    name: TestApp

  catalog:
    c1: files
    c2: images