spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medserv
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    driver-class-name: org.postgresql.Driver
  thymeleaf:
    cache: false
  sql:
    init:
      mode: never

server:
  port: 8080
