spring:
  datasource:
    url: jdbc:postgresql://localhost:3306/MedServ
    username: root
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver
    #    driver-class-name: org.postgresql.Driver
  thymeleaf:
    cache: false
  sql:
    init:
      mode: never

server:
  port: 8081
